import { jsPDF } from "jspdf";

function PDFGenerator({ record }) {
  const generatePDF = () => {
    const doc = new jsPDF();

    // Set default font
    doc.setFont("helvetica");

    // Add header with background
    doc.setFillColor(63, 81, 181); // Blue color
    doc.rect(0, 0, 220, 30, "F");

    // Title with white color
    doc.setFontSize(20);
    doc.setTextColor(255, 255, 255);
    doc.text("Attendance Report", 105, 20, { align: "center" });

    // Reset text color
    doc.setTextColor(0, 0, 0);

    // Add report details section
    doc.setFontSize(12);
    doc.text(`Date: ${record.date}`, 14, 40);

    // Add summary statistics
    doc.setFontSize(14);
    doc.setTextColor(63, 81, 181);
    doc.text("Summary", 14, 55);

    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(
      `Total Students: ${record.present.length + record.absent.length}`,
      20,
      65
    );

    // Present students count with green
    doc.setTextColor(46, 125, 50);
    doc.text(
      `Present: ${record.present.length} (${Math.round(
        (record.present.length /
          (record.present.length + record.absent.length)) *
          100
      )}%)`,
      20,
      75
    );

    // Absent students count with red
    doc.setTextColor(198, 40, 40);
    doc.text(
      `Absent: ${record.absent.length} (${Math.round(
        (record.absent.length /
          (record.present.length + record.absent.length)) *
          100
      )}%)`,
      20,
      85
    );

    // Reset color
    doc.setTextColor(0, 0, 0);

    // Add divider line
    doc.setDrawColor(200, 200, 200);
    doc.line(14, 90, 196, 90);

    // Present Students section
    doc.setFontSize(16);
    doc.setTextColor(46, 125, 50); // Dark green
    doc.text("Present Students", 14, 105);

    doc.setFontSize(12);
    let yPos = 115;
    record.present.forEach((student) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }

      // Add student card-like design
      doc.setFillColor(232, 245, 233); // Light green background
      doc.roundedRect(20, yPos - 5, 170, 8, 2, 2, "F");
      doc.setTextColor(0, 0, 0);
      doc.text(`✓ ${student.name} (${student.rollNumber})`, 25, yPos);
      yPos += 12;
    });

    // Absent Students section
    doc.setFontSize(16);
    doc.setTextColor(198, 40, 40); // Dark red
    doc.text("Absent Students", 14, yPos + 10);

    doc.setFontSize(12);
    yPos += 20;
    record.absent.forEach((student) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }

      // Add student card-like design
      doc.setFillColor(255, 235, 238); // Light red background
      doc.roundedRect(20, yPos - 5, 170, 8, 2, 2, "F");
      doc.setTextColor(0, 0, 0);
      doc.text(`✗ ${student.name} (${student.rollNumber})`, 25, yPos);
      yPos += 12;
    });

    // Add footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: "center" });
      doc.text("Generated by Attendance System", 195, 285, { align: "right" });
    }

    // Save the PDF
    doc.save(`Attendance_Report_${record.date.replace(/\//g, "-")}.pdf`);
  };

  return (
    <button
      onClick={generatePDF}
      className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 transition-colors shadow-md"
    >
      Download PDF Report
    </button>
  );
}

export default PDFGenerator;
